src/LearningManagementSystem/config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :administrators
  resources :grades
  resources :exams
  resources :courses
  resources :enrollments
  resources :students
  resources :home
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/LearningManagementSystem/app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :course
  has_many :grades, :dependent => :destroy

  validates_length_of :exam_name, :within => 1..20

  def full_exam_name
    "#{course.course_name} - #{exam_name}"
  end
end

src/LearningManagementSystem/app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  # before_action :authorize_student, only: [:index, :show]
  # before_action :authorize_administrator, only: [:show, :edit, :update, :destroy] 
  before_action :authorize, only: [:index, :show, :new, :edit, :create, :destory, :update]
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.joins(:course).select('exams.id, exams.course_id, exams.exam_name, courses.course_name').reorder('course_name ASC')
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:course_id, :exam_name)
    end
end

src/LearningManagementSystem/app/helpers/exams_helper.rb
module ExamsHelper
end

src/LearningManagementSystem/app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%= collection_select(:exam, :course_id, Course.all, :id, :full_course_name) %>
  </div>

  <div class="field">
    <%= form.label :exam_name %>
    <%= form.text_field :exam_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/LearningManagementSystem/app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

src/LearningManagementSystem/app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exams</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Semester</th>
      <th>Exam name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.course.course_name %></td>
        <td><%= exam.course.semester %>
        <td><%= exam.exam_name %></td>
        <% if current_administrator %>
          <td><%= link_to 'Show', exam %></td>
          <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
          <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_administrator %>
  <%= link_to 'New Exam', new_exam_path %>
<% end %>

src/LearningManagementSystem/app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Back', exams_path %>

src/LearningManagementSystem/app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @exam.course.course_name %>
</p>

<p>
  <strong>Exam name:</strong>
  <%= @exam.exam_name %>
</p>

<% if current_administrator %>
  <%= link_to 'Edit', edit_exam_path(@exam) %> |
<% end %>
<%= link_to 'Back', exams_path %>