src/LearningManagementSystem/config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :administrators
  resources :grades
  resources :exams
  resources :courses
  resources :enrollments
  resources :students
  resources :home
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/LearningManagementSystem/app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :exam
  belongs_to :student
  
  validates :grade, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
end

src/LearningManagementSystem/app/controllers/grades_controller.rb
class GradesController < ApplicationController
  # before_action :authorize_student, only: [:index, :show]
  # before_action :authorize_administrator, only: [:show, :edit, :update, :destroy] 
  before_action :authorize, only: [:index, :show, :new, :edit, :create, :destory, :update]
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.joins(:student, :exam).select('grades.id, grades.exam_id, exams.exam_name, grades.student_id, students.first_name, students.last_name, grades.grade')
    if current_student 
      @grades = @grades.where(grades: { student_id: current_student.id })
    end
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:exam_id, :student_id, :grade)
    end
end

src/LearningManagementSystem/app/helpers/grades_helper.rb
module GradesHelper
end

src/LearningManagementSystem/app/views/grades/_form.html.erb
<%= form_with(model: grade, local: true) do |form| %>
  <% if grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :exam_id %>
    <%= collection_select(:grade, :exam_id, Exam.all, :id, :full_exam_name) %>

  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= collection_select(:grade, :student_id, Student.all, :id, :full_name) %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.number_field(:grade, in: 0..100) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/LearningManagementSystem/app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

src/LearningManagementSystem/app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grades</h1>

<table>
  <thead>
    <tr>
      <th>Exam</th>
      <th>Student</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.exam.full_exam_name %></td>
        <td><%= "#{grade.first_name} #{grade.last_name}" %></td>
        <td><%= grade.grade %></td>
        <% if current_administrator %>
          <td><%= link_to 'Show', grade %></td>
          <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
          <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_administrator %>
  <%= link_to 'New Grade', new_grade_path %>
<% end %>

src/LearningManagementSystem/app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Back', grades_path %>

src/LearningManagementSystem/app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Exam:</strong>
  <%= @grade.exam.full_exam_name %>
</p>

<p>
  <strong>Student:</strong>
  <%= @grade.student.full_name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @grade.grade %>
</p>
<% if current_administrator %>
  <%= link_to 'Edit', edit_grade_path(@grade) %> |
<% end %>
<%= link_to 'Back', grades_path %>