src/LearningManagementSystem/config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :administrators
  resources :grades
  resources :exams
  resources :courses
  resources :enrollments
  resources :students
  resources :home
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/LearningManagementSystem/app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course

  def enrollment_gpa
    grades_total = 0
    exam_count = 0
    for exam in course.exams do
      grade = exam.grades.find_by(student_id: student_id)
      if grade
        grades_total += grade.grade
      end

      exam_count += 1
    end
    if exam_count > 0
      return grades_total / exam_count
    else
      return 'N/A'
    end
  end
end

src/LearningManagementSystem/app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  # before_action :authorize_student, only: [:index, :show]
  # before_action :authorize_administrator, only: [:show, :edit, :update, :destroy] 
  before_action :authorize, only: [:index, :show, :new, :edit, :create, :destory, :update]
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.joins(:course, :student).select('enrollments.id, enrollments.course_id, courses.course_name, courses.semester, students.first_name, students.last_name, enrollments.student_id').reorder('last_name ASC')
    if (params.has_key?(:semester))
      if (params[:semester] != 'all')
        @enrollments = @enrollments.where(courses: { semester: params[:semester] })
      end
    end

    if current_student
      @enrollments = @enrollments.where(enrollments: { student_id: current_student.id })
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:student_id, :course_id)
    end
end

src/LearningManagementSystem/app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

src/LearningManagementSystem/app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment, local: true) do |form| %>
  <% if enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <% if current_administrator %>
      <%= collection_select(:enrollment, :student_id, Student.all.order(last_name: :asc, first_name: :desc), :id, :full_name) %>
    <% elsif current_student %>
      <%= collection_select(:enrollment, :student_id, [current_student], :id, :full_name) %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= collection_select(:enrollment, :course_id, Course.all, :id, :full_course_name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/LearningManagementSystem/app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

src/LearningManagementSystem/app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<% if params[:semester] && params[:semester] != 'all' %>
  <span>Showing Current Semester: <%= params[:semester] %> <%= link_to(
            'Clear', 
            controller: 'enrollments'
            ) %></span>
  <br /> <br />
<% end %>


<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Semester</th>
      <th>Course Name</th>
      <th>GPA</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td>
          <%= link_to(
            enrollment.student.full_name, 
            controller: 'students',
            action: 'show', 
            id: enrollment.student_id
            ) %>
        </td>
        <td>
          <%= link_to(
            enrollment.semester, 
            controller: 'enrollments',
            semester: enrollment.course.semester
            ) %>
        </td>
        <td>
          <%= link_to(
            enrollment.course.course_name, 
            controller: 'courses',
            action: 'show', 
            id: enrollment.course_id
            ) %>
        </td>
        <td>
          <%= enrollment.enrollment_gpa %>
        </td>
        <% if current_administrator %>
          <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <% end %>
        <td><%= link_to 'Drop', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

src/LearningManagementSystem/app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Back', enrollments_path %>

src/LearningManagementSystem/app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @enrollment.student.full_name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @enrollment.course.full_course_name %>
</p>

<% if current_administrator %>
  <%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<% end %>
<%= link_to 'Back', enrollments_path %>